### ISSUE TITLE
Beremiz doesn't start if installed with Windows installer 

### ISSUE THREAD

**Issue by gamaudric** [beremiz/beremiz_public_dist#8]
Hello,
I recompiled the Windows installer from source (compiled with docker), everything is created as expected (beremiz-nsis-installer.exe).
One the installer finished its job, I can't launch Beremiz (double click on the link doesn't do anything).
Maybe I have done something wrong?

**Comment by etisserant** [comment]
It seems OK.
Please open a shell (CMD) and replicate shortcut's launch there.
You can copy shortcut's launch parameters in properties of the link (right-click properties).
Then you should be able to see Beremiz IDE output, possibly including error that prevents launching.

**Comment by gamaudric** [comment]
Here is the cmd output (empty):
![image](https://github.com/user-attachments/assets/1237ad96-00ed-47a9-897b-738dc85a2d71)

**Comment by etisserant** [comment]
To obtain more output, you may replace pythonw.exe by python.exe

**Comment by gamaudric** [comment]
Indeed with python.exe I have some output that complain about missing DLL in wx library:
![image](https://github.com/user-attachments/assets/825842d6-88cf-48a5-8e04-2ee2dbc9bd14)

**Comment by etisserant** [comment]
Strange. Core DLL is supposed to be just aside core.py. Do you have same result with latest release ?

**Comment by gamaudric** [comment]
I just installed a new Beremiz 1.4 with the .exe provided in GitHub and it's also fail with the same error.

**Comment by etisserant** [comment]
Pour la prochaine fois: release should have been first thing to test and report.
Anyhow.
You must have something in your system messing with Beremiz install. Anything like native python, wxPython or MSYS2 installed ?
Anything suspicious in "echo %PATH%" ?

**Comment by gamaudric** [comment]
I have Python 3.8 and 3.11 installed on windows, and 2 separate version of previous beremiz version.
Nothing else seem to be weird in the PATH

**Comment by etisserant** [comment]
Maybe problem is in environment ?
`C:\install_path\python.exe -c "import os,pprint; pprint.pp(os.environ.copy())"`

Is that happening on Windows 11 ?

**Comment by etisserant** [comment]
In case some another MSYS2 install would conflict happens, try launch python interpreter with launcher `msys64/ucrt64.exe`.
IS there already some MSYSTEM variable set in your env ?

**Comment by etisserant** [comment]
An [MSYS2 launcher](https://www.msys2.org/wiki/Launchers/) should set MSYSTEM anyhow. I forgot this apparently. What happens if you call `set MSYSTEM=UCRT64` in cmd.exe before launching python ?

**Comment by etisserant** [comment]
d30d195332ea26a5b6767683868fba10f1efefd8 fixes missing MSYSTEM. Please give a try and report.

**Comment by gamaudric** [comment]
I just pulled the code of both Beremiz and Beremiz_public_dist, recompiled and now everything is working!
Thanks!
